// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qntezrozqejnkvndkvqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFudGV6cm96cWVqbmt2bmRrdnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjE0MDUsImV4cCI6MjA2OTc5NzQwNX0.Vjdy_r1otHwqKugsAcchIuBdcOJ6aAcEpfuG9RL99_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});